'reinit';
'open ../ctl/rmse_fsena-fsena.ctl';
'set t 1 204';
'set grads off';
'set xlab off';
'set ccolor 1';
'set cstyle 1';
'set cmark  0';
'd rmse_fa';
'set ylpos 0 r';
'set ccolor 1';
'set cstyle 1';
'set cmark  2';
'd fa';
'run cbar_line -m "0" 2 -l 1 1 -t "SD of canopy sensible heat flux (W/m`a2`n)" "canopy sensible heat flux (W/m`a2`n)" -p'; 
'enable print /g4/lix/rmse_fsena-fsena.gmf';
'print';
'disable print';
'disable fwrite';
;
