'reinit';
'open ../ctl/rmse_fgrnd-fgrnd.ctl';
'set t 1 204';
'set grads off';
'set xlab off';
'set ccolor 1';
'set cstyle 1';
'set cmark  0';
'd rmse_fd';
'set ylpos 0 r';
'set ccolor 1';
'set cstyle 1';
'set cmark  2';
'd fd';
'run cbar_line -m "0" 2 -l 1 1 -t "SD of ground heat flux (W/m`a2`n)" "ground heat flux (W/m`a2`n)" -p'; 
'enable print /g4/lix/rmse_fgrnd-fgrnd.gmf';
'print';
'disable print';
'disable fwrite';
;
