'reinit';
'open ../ctl/rmse_fseng-fseng.ctl';
'set t 1 204';
'set grads off';
'set xlab off';
'set ccolor 1';
'set cstyle 1';
'set cmark  0';
'd rmse_fg';
'set ylpos 0 r';
'set ccolor 1';
'set cstyle 1';
'set cmark  2';
'd fg';
'run cbar_line -m "0" 2 -l 1 1 -t "SD of ground sensible heat flux (W/m`a2`n)" "ground sensible heat flux (W/m`a2`n)" -p'; 
'enable print /g4/lix/rmse_fseng-fseng.gmf';
'print';
'disable print';
'disable fwrite';
;
