#define OFFLINE
#undef  COUP_CSM
#define RDGRID
#undef  SOILINI
#undef  BATS
#undef  SIB2
#undef  IGBP
#undef  USGS
#undef  EcoDynamics
#define PFT
#define DGVM
#define BARE
#undef  DyN
#undef  SINGLE
#define LANDONLY
#undef  LAND_SEA
#undef  SINGLE_POINT
#undef  GLACIER
#undef  MAPMASK
#undef  METMASK
#define PRINCETON
#undef  GSWP2
#define WR_YEARLY
#undef  RTM
#undef  SPMD
#define LINUX
#define SPINUP
#define NCHIST
#undef  DAILYRST
#undef  MYBUG
#undef  RESTART_FMT1
#define CMIP
